Repository ShaneKent/PyEventLogViewer, pull requests merged in 2018-02, with the labels that each got.

#103 Add timezone offset configuration to view menu
  .gitignore
  winlogtimeline/ui/ui.py
  winlogtimeline/util/logs.py
  winlogtimeline/util/project.py
Labels: enhancement

#104 Updated tests for 1074.
  tests/test_parser.py
Labels: enhancement

#106 Change color tags to use event source as well as event id
  winlogtimeline/ui/tag_settings.py
  winlogtimeline/ui/ui.py
  winlogtimeline/util/config/config.json
Labels: enhancement

#110 Improve error handling in parser
  winlogtimeline/collector/parser.py
  winlogtimeline/ui/ui.py
Labels: bugfix, high priority

#113 Export improvements
  winlogtimeline/collector/parser.py
  winlogtimeline/ui/export_timeline.py
  winlogtimeline/ui/ui.py
  winlogtimeline/util/logs.py
Labels: enhancement

#115 Fix status bar resizing on windows
  winlogtimeline/ui/ui.py
Labels: bugfix

#125 Convert parser to use event source and event id
  tests/test_collect.py
  tests/test_parser.py
  winlogtimeline/collector/collect.py
  winlogtimeline/collector/parser.py
Labels: enhancement

#128 Clean up test files and add event parsing tests
  setup.py
  tests/test_collect.py
  tests/test_parser.py
Labels: enhancement, testing

#131 Change tag settings listbox to treeview
  winlogtimeline/ui/tag_settings.py
  winlogtimeline/util/config/config.json
Labels: enhancement

#136 Closes #84.
  winlogtimeline/ui/ui.py
Labels: enhancement

#135 Add import failure cleanup, fix bug in export process
  tests/test_parser.py
  winlogtimeline/ui/ui.py
  winlogtimeline/util/project.py
Labels: bugfix, enhancement
